[container.image]
repository="ramilu90" # Docker hub repository name.
name="airline-service" # container name
tag="1.0.0"

[[cloud.config.envs]]
key_ref="MOCK_API_BASE_URL"
config_name="ballerina-values"